### ISSUE TITLE
Immortal &nbsp;s

### ISSUE THREAD

**Issue by dwtkns** [newsdev/archieml.org#17]
I've run into a situation a couple of times now where adding a line break and then removing it (over the course of editing) results in one or more `&nbsp;` in the generated data object that are hard to get rid of. 

As far as I've seen these are always inserted where regular spaces should be. Backspacing and adding a new space manually doesn't seem to help - my only solution so far has been to copy the text of interest into an editor that strips out formatting, like Sublime, and then paste back into the document.

**Comment by archietse** [comment]
This might be an issue with our data downloader, but not sure.

In the meantime, you can copy the offending text and immediately paste it back without formatting by `cmd-C` and then `cmd-shift-V`.

**Comment by abstrctn** [comment]
I believe we fixed this in our dataloader by passing the Google Docs source through a filter that did something like this in order to convert non-breaking spaces into "regular" spaces:

`parsedText = parsedText.replace(new RegExp(String.fromCharCode(160), 'g'), ' ');`
