### ISSUE TITLE
Ignore any text written after brackets or colon commands

### ISSUE THREAD

**Issue by archietse** [newsdev/archieml.org#9]
It would be nice to allow comments (ie. ignored text) after brackets or colon commands so that we can add notes inline with the commands without having additional brackets. This would be similar to how we ignore any text after the `:ignore` command. Here are some examples:

```
[sections] here are the main sections of the project
id:1
text: Lorem
id:2
text: Ipsum
[] this is the end of the main sections

[notes] here are the notes for the project
id:1
text: Lorem
:skip we should leave this note out until it's checked
id:2
text: Ipsum
:endskip
[] this is the end of the notes
```

**Comment by abstrctn** [comment]
Hey @archietse - this behavior should already be in place for all "special" lines:
- :token
- {token}
- [token]
- {}
- []

The following line is included in the spec to suggest this, but I admit it's very unclear, and doesn't specify enough that it applies to all special lines _except_ `key: value` and `* value`:

> Special lines are defined by their beginnings; all text after the patterns mentioned above are valid and do not affect the line's status.

We can rewrite that / if anyone has any suggestions for it, they're welcome, as are suggestions for a word other than "special" to describe lines that are semantically significant...
